//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Kot.java
//  @ Date : 15.03.2023
//  @ Author : 
//
//
package org.example;



public class Kot extends Ssak {
	public boolean hasWhiskers;
	public void purr() {
		System.out.println("The cat is purring...");
	}
	
	public void cleanYourself() {
		System.out.println("The cat is cleaning itself!");
	}

	public Kot(int age, int height, String name, String furColor, boolean hasWhiskers) {
		super(age, height, name, furColor);
		this.hasWhiskers = hasWhiskers;
	}
}
