//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : KotNorweskiLesny.java
//  @ Date : 15.03.2023
//  @ Author : 
//
//
package org.example;



public class KotNorweskiLesny extends Kot {
	public boolean isSheding;
	public void useScratchingPost() {
		System.out.println( getName()+ " is scratching the scratch post!");
	}

	public KotNorweskiLesny(int age, int height, String name, String furColor, boolean hasWhiskers, boolean isSheding) {
		super(age, height, name, furColor, hasWhiskers);
		this.isSheding = isSheding;
	}
}
