package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.java
//  @ Date : 15.03.2023
//  @ Author : 
//
//




public class Pies extends Ssak {
	public boolean isMixed;
	private String race;
	public void chaseTail() {
		System.out.println("The dog is chasing it's tail!");
	}

	public boolean isMixed() {
		return isMixed;
	}

	public void setMixed(boolean mixed) {
		isMixed = mixed;
	}

	public String getRace() {
		return race;
	}

	public void setRace(String race) {
		this.race = race;
	}

	public Pies(int age, int height, String name, String furColor, boolean isMixed, String race) {
		super(age, height, name, furColor);
		this.isMixed = isMixed;
		this.race = race;
	}
}
