package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.java
//  @ Date : 15.03.2023
//  @ Author : 
//
//




public class Ssak {
	private int age;
	private int height;
	private String name;
	private String furColor;

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getHeight() {
		return height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFurColor() {
		return furColor;
	}

	public void setFurColor(String furColor) {
		this.furColor = furColor;
	}

	public Ssak(int age, int height, String name, String furColor) {
		this.age = age;
		this.height = height;
		this.name = name;
		this.furColor = furColor;
	}
}
