//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Americano.cpp
//  @ Date : 22.06.2023
//  @ Author : 
//
//


#include "Americano.h"

void Americano::brewCoffee() {
    cout<<"Brewing Americano Coffee"<<endl;
}

void Americano::addCondiments() {
    cout<<"Adding sugar"<<endl;
}

bool Americano::customerWantsCondiments() {
    return true;
}


