//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Americano.h
//  @ Date : 22.06.2023
//  @ Author : 
//
//


#if !defined(_AMERICANO_H)
#define _AMERICANO_H

#include "Coffee.h"

class Americano : public Coffee {
public:
	void brewCoffee() override;
	void addCondiments() override;
    bool customerWantsCondiments() override;
};

#endif  //_AMERICANO_H
