//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Coffee.cpp
//  @ Date : 22.06.2023
//  @ Author : 
//
//


#include "Coffee.h"

void Coffee::brew() {
    boilWater();
    brewCoffee();
    pourToCup();
    if(customerWantsCondiments()){
        addCondiments();
    }
}

void Coffee::boilWater() {
    cout << "Boiling water" <<endl;
}

void Coffee::pourToCup() {
    cout <<"Pouring coffee to the cup" <<endl;
}

