//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Coffee.h
//  @ Date : 22.06.2023
//  @ Author : 
//
//


#if !defined(_COFFEE_H)
#define _COFFEE_H
#include <iostream>
using namespace std;

class Coffee {
public:
	void brew();
	void boilWater();
	virtual void brewCoffee() = 0;
	virtual void addCondiments() = 0;
	virtual bool customerWantsCondiments() = 0;
    void pourToCup();
};

#endif  //_COFFEE_H
