//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Espresso.cpp
//  @ Date : 22.06.2023
//  @ Author : 
//
//


#include "Espresso.h"

void Espresso::brewCoffee() {
    cout<<"Brewing Espresso coffee"<<endl;
}

void Espresso::addCondiments() {
    cout<<"Giving the customer a glass of water"<<endl;
}

bool Espresso::customerWantsCondiments() {
    return false;
}



