//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Cinema.cpp
//  @ Date : 22.03.2023
//  @ Author : 
//
//


#include "Cinema.h"

Cinema::Cinema(string cinemaName) {
    this->cinemaName = cinemaName;
    cout<< "Welcome to the cinema named " << cinemaName <<endl;
    movie = new Movie;
}

Cinema::~Cinema() {
    delete movie;
}

void Cinema::getMovieSchedule() {
    cout << movie->getMovieTitle()<<" "<<movie->getMovieHour() <<endl;
}

void Cinema::setMovieSchedule(string movieTitle, string movieHour) {
    movie->setMovieTitle(movieTitle);
    movie->setMovieHour(movieHour);
}

