//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Cinema.h
//  @ Date : 22.03.2023
//  @ Author : 
//
//


#if !defined(_CINEMA_H)
#define _CINEMA_H


#include "Movie.h"

class Cinema {
public:
	Cinema(string cinemaName);
	~Cinema();
	void getMovieSchedule();
	void setMovieSchedule(string movieTitle, string movieHour);
private:
	Movie* movie;
	string cinemaName;
};

#endif  //_CINEMA_H
