//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : A.h
//  @ Date : 17.05.2023
//  @ Author : 
//
//


#if !defined(_A_H)
#define _A_H
#include "B.h"

class A {
public:
	void setB(B* b);
	void aFunction();
private:
    B *b;
    int n = 0;
};

#endif  //_A_H
