//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : B.cpp
//  @ Date : 17.05.2023
//  @ Author : 
//
//


#include "B.h"

void B::setC(C* c) {
    this->c = c;
}

void B::bFunction() {
    cout<< "B function" <<endl;
}

