//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : B.h
//  @ Date : 17.05.2023
//  @ Author : 
//
//


#if !defined(_B_H)
#define _B_H
#include <iostream>
#include "C.h"
using namespace std;

class C;
class B {
public:
	void setC(C* c);
	void bFunction();
private:
    C* c;
};

#endif  //_B_H
