//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : C.cpp
//  @ Date : 17.05.2023
//  @ Author : 
//
//


#include "C.h"

void C::setB(B* b) {
    this->b = b;
}

void C::cFunction() {
    if (x > 0){
        b->bFunction();
    }
}

