//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : C.h
//  @ Date : 17.05.2023
//  @ Author : 
//
//


#if !defined(_C_H)
#define _C_H
#include "B.h"

class B;
class C {
public:
	void setB(B* b);
	void cFunction();
private:
    B *b;
    int x;
};

#endif  //_C_H
