//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Cinema.cpp
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#include "Cinema.h"

Cinema::Cinema(string cinemaName) {
    this->cinemaName = cinemaName;
    cout << "Welcome to " <<cinemaName<< " !"<<endl;
    movies.push_back(new Movie("Roundhay Garden Scene","8:00"));
}

Cinema::~Cinema() {
}

void Cinema::getMovieSchedule() {
    for (const auto &item: movies) {
        cout << "Title : " << item->getMovieTitle() << " | Hour : " <<item->getMovieHour() <<endl;
    }
}

void Cinema::getMovieDataAtIndex(int i) {
    cout <<"The movie is called " << movies.at(i)->getMovieTitle() << " and it starts at "
        << movies.at(i)->getMovieHour()<<endl;
}

void Cinema::moviePushBack(Movie* movie) {
    movies.push_back(movie);
}

void Cinema::moviePopBack() {
    movies.pop_back();
}

