//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Cinema.h
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#if !defined(_CINEMA_H)
#define _CINEMA_H
#include "Movie.h"
#include <vector>

class Cinema {
public:
	Cinema(string cinemaName);
	~Cinema();
	void getMovieSchedule();
	void getMovieDataAtIndex(int i);
	void moviePushBack(Movie* movie);
	void moviePopBack();
private:
	string cinemaName;
	vector<Movie*> movies;
};

#endif  //_CINEMA_H
