//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Movie.h
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#if !defined(_MOVIE_H)
#define _MOVIE_H
#include <iostream>
#include <string>
using namespace std;

class Movie {
public:
	Movie(string movieTitle, string movieHour);
	~Movie();
	string getMovieTitle();
	string getMovieHour();
	void setMovieTitle(string movieTitle);
	void setMovieHour(string movieHour);
private:
	string movieTitle;
	string movieHour;
};

#endif  //_MOVIE_H
