//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Employee.cpp
//  @ Date : 30.03.2023
//  @ Author : 
//
//


#include "Employee.h"

int Employee::getID() {
    return id;
}

string Employee::getName() {
    return name;
}

bool Employee::getManagerInfo() {
    return isManager;
}

int Employee::getSalary() {
    return salary;
}

void Employee::setID(int id) {
    this->id = id;
}

void Employee::setName(string name) {
    this->name = name;
}

Employee::Employee(int id, string name, bool isManager, int salary) {
    this->id = id;
    this->name = name;
    this->isManager = isManager;
    this->salary = salary;
}

void Employee::getFullEmpInfo() {
    cout << "Employee with ID : " <<this->getID() << " || Name : "<< this->getName()
    <<" || Is"<<(this->getManagerInfo() ? "":" not") << " a manager || Salary : " <<this->getSalary()<<endl;
}

void Employee::setManagement(bool isManager, bool auth){
    if(auth){
        this->isManager = isManager;
    }else{
        cout << "You can't promote yourself to a manager without permission!" <<endl;
    }
}
void Employee::setSalary(int salary, bool auth) {
    if(auth){
        this->salary = salary;
    }else{
        cout << "You cannot change your salary!" <<endl;
    }
}


