//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Manager.cpp
//  @ Date : 30.03.2023
//  @ Author : 
//
//


#include "Manager.h"

void Manager::setManagerAttrToEmpID(int id, bool isManager) {
    for(Employee& employee : employees){
        if(employee.getID() == id ) {
            employee.setManagement(!isManager, true);
            return;
        }
    }
    cout << "Wrong ID!" <<endl;
}

void Manager::fireEmployeeWithID(int id) {
    int idx=0;
    for (Employee employee: employees) {
        if(employee.getManagerInfo()){
            cout << "You can't fire another manager!" <<endl;
        }else if(employee.getID() == id){
            employees.erase(employees.begin()+idx);
        }
        idx++;
    }
}

Manager::Manager(int id, const string &name, bool isManager, int salary)
: Employee(id, name,true,salary) {}

void Manager::addEmployeeToTeam(Employee emp) {
    employees.push_back(emp);
}

void Manager::getEmployees(){
    if(employees.empty()){
        cout << "You don't have any employees!" <<endl;
    }
    for(Employee employee: employees){
        employee.getFullEmpInfo();
    }
}
