//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.h
//  @ Date : 15.03.2023
//  @ Author : 
//
//


#if !defined(_JAMNIK_H)
#define _JAMNIK_H

#include "Pies.h"

class Jamnik : public Pies {
public:
    Jamnik(int age, int height, string name, string furColor,bool isMixed, string race, bool floppyEars);
	bool floppyEars;
	void catchABall();
};

#endif  //_JAMNIK_H
