//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 15.03.2023
//  @ Author : 
//
//

#include <iostream>
#include "Jamnik.h"
using namespace std;
Jamnik::Jamnik(int age, int height, string name, string furColor, bool isMixed, string race, bool floppyEars) :
Pies(age, height, name, furColor,isMixed,race) {
    this->floppyEars = floppyEars;
}
void Jamnik::catchABall() {
    cout << "Catched a ball!" <<endl;
}

