//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.h
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#if !defined(_JAMNIK_H)
#define _JAMNIK_H

#include "Pies.h"

class Jamnik : public Pies {
};

#endif  //_JAMNIK_H
