//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kapibara.cpp
//  @ Date : 09.03.2023
//  @ Author : 
//
//

#include <iostream>
#include "Kapibara.h"
using namespace std;

void Kapibara::swim() {
    cout << "The Capybara is swimming!"<<endl;
}

