//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kot.h
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#if !defined(_KOT_H)
#define _KOT_H

#include "Ssak.h"

class Kot : public Ssak {
public:
	void purr();
	void cleanYourself();
    void makeNoise() override;
};

#endif  //_KOT_H
