//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kot.cpp
//  @ Date : 15.03.2023
//  @ Author : 
//
//

#include <iostream>
#include "Kot.h"
using namespace std;
Kot::Kot(int age, int height, string name, string furColor, bool hasWhiskers)
: Ssak(age,height,name,furColor) {
    this->hasWhiskers = hasWhiskers;
}
void Kot::purr() {
    cout << "The cat is purring..." <<endl;
}

void Kot::cleanYourself() {
    cout << "The cat is cleaning itself!" <<endl;
}

