//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kot.h
//  @ Date : 15.03.2023
//  @ Author : 
//
//


#if !defined(_KOT_H)
#define _KOT_H

#include "Ssak.h"

class Kot : public Ssak {
public:
    Kot(int age, int height, string name, string furColor, bool hasWhiskers);
	bool hasWhiskers;
	void purr();
	void cleanYourself();
};

#endif  //_KOT_H
