//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kot.cpp
//  @ Date : 09.03.2023
//  @ Author : 
//
//

#include <iostream>
#include "Kot.h"
using namespace std;

void Kot::purr() {
    cout << "Purrr....." <<endl;
}

void Kot::cleanYourself() {
    cout << "The cat is licking itself" <<endl;
}

