//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KotNorweskiLesny.h
//  @ Date : 15.03.2023
//  @ Author : 
//
//


#if !defined(_KOTNORWESKILESNY_H)
#define _KOTNORWESKILESNY_H

#include "Kot.h"

class KotNorweskiLesny : public Kot {
public:
    KotNorweskiLesny(int age, int height, string name, string furColor,bool hasWhiskers, bool isSheding);
	bool isSheding;
	void useScratchingPost();
};

#endif  //_KOTNORWESKILESNY_H
