//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KotNorweskiLesny.cpp
//  @ Date : 15.03.2023
//  @ Author : 
//
//

#include <iostream>
#include "KotNorweskiLesny.h"
using namespace std;
KotNorweskiLesny ::KotNorweskiLesny(int age, int height, string name, string furColor, bool hasWhiskers,bool isSheding)
: Kot(age,height,name,furColor,hasWhiskers){
    this->isSheding = isSheding;
}
void KotNorweskiLesny::useScratchingPost() {
    cout << getName() <<" is scratching the scratch post!" <<endl;
}

