//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KotNorweskiLesny.h
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#if !defined(_KOTNORWESKILESNY_H)
#define _KOTNORWESKILESNY_H

#include "Kot.h"

class KotNorweskiLesny : public Kot {
};

#endif  //_KOTNORWESKILESNY_H
