//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#include<iostream>
#include "Pies.h"
using namespace std;

void Pies::chaseTail() {
    cout << "The dog is chasing it's tail!" <<endl;
}

void Pies::makeNoise() {
    cout << "Bark" <<endl;
}

