//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"

class Pies : public Ssak {
public:
	void chaseTail();
    void makeNoise() override;
};

#endif  //_PIES_H
