//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 15.03.2023
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H
using namespace std;
#include <string>


class Ssak {
public:
	int getAge();
	int getHeight();
	string getName();
	void setAge(int value);
	void setHeight(int height);
	void setName(string name);
	string getFurColor();
	void setFurColor(string furColor);
	Ssak(int age, int height, string name, string furColor);
private:
	int age;
	int height;
	string name;
	string furColor;
};

#endif  //_SSAK_H
