//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 15.03.2023
//  @ Author : 
//
//


#include "Ssak.h"
using namespace std;

int Ssak::getAge() {
    return age;
}

int Ssak::getHeight() {
    return height;
}

string Ssak::getName() {
    return name;
}

void Ssak::setAge(int value) {
    this->age = value;
}

void Ssak::setHeight(int height) {
    this->height = height;
}

void Ssak::setName(string name) {
    this->name = name;
}

string Ssak::getFurColor() {
    return furColor;
}

void Ssak::setFurColor(string furColor) {
    this->furColor = furColor;
}
Ssak::Ssak(int age, int height, string name, string furColor) {
    this->age = age;
    this->height = height;
    this->name = name;
    this->furColor = furColor;
}

