//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Company.h
//  @ Date : 22.03.2023
//  @ Author : 
//
//


#if !defined(_COMPANY_H)
#define _COMPANY_H

#include "Employee.h"

class Company {
public:
	Company(string companyName);
	Employee getEmployee();
	void setEmployee(int id, string name);
    string getCompanyName();
    void setCompanyName(string companyName);

private:
	Employee employee;
	string companyName;
};

#endif  //_COMPANY_H
