//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Company.cpp
//  @ Date : 22.03.2023
//  @ Author : 
//
//


#include "Company.h"
#include "Employee.h"

Company::Company(string companyName) {
    this->companyName = companyName;
}

Employee Company::getEmployee() {
    return employee;
}

void Company::setEmployee(int employeeID, string employeeName) {
    employee.setID(employeeID);
    employee.setName(employeeName);
}

string Company::getCompanyName() {
    return companyName;
}

void Company::setCompanyName(string companyName) {
    Company::companyName = companyName;
}

