//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : InternetStoreSystem.h
//  @ Date : 19.04.2023
//  @ Author : 
//
//


#if !defined(_INTERNETSTORESYSTEM_H)
#define _INTERNETSTORESYSTEM_H
#include "User.h"
#include <vector>
#include <iostream>
#include <algorithm>
using namespace std;
class User;
class InternetStoreSystem {
public:
	void authenticate(User *user);
	void registerUser(User *user);
	InternetStoreSystem(string name);
	void getUsers();

    virtual ~InternetStoreSystem();

private:
	string name;
	vector<User*> users;
};

#endif  //_INTERNETSTORESYSTEM_H
