//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : InternetStoreSystem.cpp
//  @ Date : 19.04.2023
//  @ Author : 
//
//


#include "InternetStoreSystem.h"

void InternetStoreSystem::authenticate(User *user) {
    int idToFind = user->getID();
    auto search = find_if(users.begin(), users.end(),[idToFind](User *targetUser){return targetUser->getID() == idToFind; });
    if(search != users.end()){
        User* foundUser = *search;
        cout << "Successfully logged in!" <<endl;
        cout<< "Welcome back, " <<foundUser->getUsername() <<"!"<<endl;
    } else{
        registerUser(user);
    }
}
void InternetStoreSystem::registerUser(User *user) {
    user->setID(users.size() + 1);
    users.push_back(user);
    cout<<"You have been registered, " <<user->getUsername() <<"! " <<endl;
}


InternetStoreSystem::InternetStoreSystem(string name) {
    this->name = name;
}

void InternetStoreSystem::getUsers() {
    for (const auto &user: users) {
        user->printData();
    }
}

InternetStoreSystem::~InternetStoreSystem() {
    for (const auto &user: users) {
        delete user;
    }
    users.clear();
}
