//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.h
//  @ Date : 19.04.2023
//  @ Author : 
//
//


#if !defined(_USER_H)
#define _USER_H
#include "InternetStoreSystem.h"
#include <iostream>
using namespace std;
class InternetStoreSystem;
class User {
public:
	void login(InternetStoreSystem *internetStore);
	void printData();
	User(string username, string password);
	void setID(int id);
	int getID();
	string getUsername();
	string getPassword();
	void setUsername(string username);
	void setPassword(string password);
private:
	int id;
	string username;
	string password;
};

#endif  //_USER_H
