//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CarToRent.h
//  @ Date : 21.03.2023
//  @ Author : 
//
//


#if !defined(_CARTORENT_H)
#define _CARTORENT_H


#include "Client.h"
#include <string>
using namespace std;
class Client;
class CarToRent {
private:
    Client* client;
    string name;
public:
	Client* getClient();
	void setClient(Client* client);
	string getName();
	void setName(string name);
	CarToRent(string name);



};

#endif  //_CARTORENT_H
