//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.cpp
//  @ Date : 21.03.2023
//  @ Author : 
//
//


#include "Client.h"
#include "CarToRent.h"

CarToRent* Client::getRentedCar() {
    return rentedCar;
}

void Client::rentCar(CarToRent* rentedCar) {
    this->rentedCar = rentedCar;
}

int Client::getID() {
    return id;
}

string Client::getName() {
    return name;
}

void Client::setID(int id) {
    this->id = id;
}

void Client::setName(string name) {
    this->name = name;
}

Client::Client(int id, string name)  {
    this->id = id;
    this->name = name;
}

