//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.h
//  @ Date : 24.05.2023
//  @ Author :
//
//

#if !defined(_KURS_H)
#define _KURS_H

#include <string>
#include <vector>
#include <unordered_map>

class Student;
class Wykladowca;

using namespace std;

class Kurs {
public:
	Kurs(int id, string nazwa, Wykladowca* prowadzacy);
	bool dolacz(Student* student);
	void wyswietlStudentow();
	void wyswietlWykladowce();
	void wyswietlOceny();
	bool czyNalezy(Student* student);
	void setNazwa(string nazwa);
	bool setOcena(Student* student, float ocena);
	float getOcena(Student* student);
	int getId();
	string getNazwa();
	Wykladowca& getProwadzacy();
	vector<Student*> getUczestnicy();
private:
	int id;
	string nazwa;
	Wykladowca* prowadzacy;
	vector<Student*> uczestnicy;
	unordered_map<Student*, float> oceny;
};

#endif  //_KURS_H
