//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 24.05.2023
//  @ Author : 
//
//

#if !defined(_STUDENT_H)
#define _STUDENT_H

#include "Uzytkownik.h"
#include <string>

using namespace std;

class Student : public Uzytkownik {
public:
	Student(string login, string haslo, string nazwisko);
};

#endif  //_STUDENT_H
