//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 24.05.2023
//  @ Author : 
//
//

#include "Student.h"

Student::Student(string login, string haslo, string nazwisko) : Uzytkownik(login, haslo, nazwisko) {}
