//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczelnia.h
//  @ Date : 24.05.2023
//  @ Author :
//
//

#if !defined(_UCZELNIA_H)
#define _UCZELNIA_H

#include <string>
#include <vector>
#include <unordered_map>

class Kurs;
class Student;
class Uzytkownik;
class Wiadomosc;
class Wykladowca;

using namespace std;

class Uczelnia {
public:
	Uczelnia(string nazwa);
	Uzytkownik* zaloguj(string login, string haslo);
	bool zarejestruj(string login, string haslo, string nazwisko);
	bool zarejestrujWykladowce(string login, string haslo, string nazwisko);
	bool wyslijWiadomosc(Uzytkownik* nadawca, string odbiorca, string temat, string tresc);
	void wyswietlStudentow();
	void wyswietlWykladowcow();
	void wyswietlKursy();
	void wyswietlKursy(Uzytkownik* uzytkownik);
	void wyswietlOceny(Student* student);
	void wyswietlWiadomosci(Uzytkownik* uzytkownik);
	Kurs* utworzKurs(string nazwa, Wykladowca* prowadzacy);
	Kurs* getKurs(int id);
	vector<Kurs*> getKursy();
	vector<Kurs*> getKursy(Uzytkownik* uzytkownik);
	Uzytkownik* getUzytkownik(string login);
	string getNazwa();
	vector<Wiadomosc*> getWiadomosci(Uzytkownik* uzytkownik);
private:
	string nazwa;
	unordered_map<string, Uzytkownik*> uzytkownicy;
	vector<Kurs*> kursy;
	vector<Wiadomosc*> wiadomosci;
};

#endif  //_UCZELNIA_H
