//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.h
//  @ Date : 24.05.2023
//  @ Author : 
//
//

#if !defined(_UZYTKOWNIK_H)
#define _UZYTKOWNIK_H

#include <string>

using namespace std;

class Uzytkownik {
public:
	Uzytkownik(string login, string haslo, string nazwisko);
	string getLogin();
	string getHaslo();
	string getNazwisko();
	void setHaslo(string haslo);
	void setNazwisko(string nazwisko);
	virtual ~Uzytkownik() {}
private:
	string login;
	string haslo;
	string nazwisko;
};

#endif  //_UZYTKOWNIK_H
