//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.cpp
//  @ Date : 24.05.2023
//  @ Author : 
//
//

#include "Uzytkownik.h"

Uzytkownik::Uzytkownik(string login, string haslo, string nazwisko) {
    this->login = login;
    this->haslo = haslo;
    this->nazwisko = nazwisko;
}

string Uzytkownik::getLogin() {
    return this->login;
}

string Uzytkownik::getHaslo() {
    return this->haslo;
}

string Uzytkownik::getNazwisko() {
    return this->nazwisko;
}

void Uzytkownik::setHaslo(string haslo) {
    this->haslo = haslo;
}

void Uzytkownik::setNazwisko(string nazwisko) {
    this->nazwisko = nazwisko;
}

