//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wiadomosc.h
//  @ Date : 24.05.2023
//  @ Author : 
//
//

#if !defined(_WIADOMOSC_H)
#define _WIADOMOSC_H

#include <string>

class Uzytkownik;

using namespace std;

class Wiadomosc {
public:
	Wiadomosc(Uzytkownik* nadawca, Uzytkownik* odbiorca, string temat, string tresc);
	Uzytkownik& getNadawca();
	Uzytkownik& getOdbiorca();
	string getTemat();
	string getTresc();
private:
	Uzytkownik* nadawca;
	Uzytkownik* odbiorca;
	string temat;
	string tresc;
};

#endif  //_WIADOMOSC_H
