//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.cpp
//  @ Date : 24.05.2023
//  @ Author : 
//
//

#include "Wykladowca.h"

Wykladowca::Wykladowca(string login, string haslo, string nazwisko) : Uzytkownik(login, haslo, nazwisko) {}
