//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.h
//  @ Date : 24.05.2023
//  @ Author : 
//
//

#if !defined(_WYKLADOWCA_H)
#define _WYKLADOWCA_H

#include "Uzytkownik.h"
#include <string>

using namespace std;

class Wykladowca : public Uzytkownik {
public:
	Wykladowca(string login, string haslo, string nazwisko);
};

#endif  //_WYKLADOWCA_H
