//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Cook.h
//  @ Date : 21.03.2023
//  @ Author : 
//
//


#if !defined(_COOK_H)
#define _COOK_H

#include "Food.h"
#include <string>
using namespace std;

class Cook {
public:
	Food createFood(string name, int id, int price);
	string getName();
	void setName(string name);
private:
	string name;
};

#endif  //_COOK_H
