//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Food.h
//  @ Date : 21.03.2023
//  @ Author : 
//
//


#if !defined(_FOOD_H)
#define _FOOD_H
#include <string>
using namespace std;

class Food {
public:
	string getName();
	int getID();
	int getPrice();
	void setName(string name);
	void setID(int id);
	void setPrice(int price);
	Food(int id, string name, int price);

    Food(const string &name, int id, int price);

private:
	string name;
	int id;
	int price;
};

#endif  //_FOOD_H
