//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Food.cpp
//  @ Date : 21.03.2023
//  @ Author : 
//
//


#include "Food.h"

string Food::getName() {
    return name;
}

int Food::getID() {
    return id;
}

int Food::getPrice() {
    return price;
}

void Food::setName(string name) {
    this->name = name;
}

void Food::setID(int id) {
    this->id = id;
}

void Food::setPrice(int price) {
    this->price = price;
}

Food::Food(const string &name, int id, int price) : name(name), id(id), price(price) {}
