//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : InternetProvider.h
//  @ Date : 21.03.2023
//  @ Author : 
//
//


#if !defined(_INTERNETPROVIDER_H)
#define _INTERNETPROVIDER_H
#include <iostream>
#include <string>
using namespace std;

class InternetProvider {
public:
	string getName();
	void setName(string name);
	void connectToTheInternet();
private:
	string name;
};

#endif  //_INTERNETPROVIDER_H
