//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : InternetProvider.cpp
//  @ Date : 21.03.2023
//  @ Author : 
//
//


#include "InternetProvider.h"
string InternetProvider::getName() {
    return name;
}

void InternetProvider::setName(string name) {
    this->name = name;
}

void InternetProvider::connectToTheInternet() {
    cout<< "Connected to the internet!" <<endl;
}

