//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.cpp
//  @ Date : 16.03.2023
//  @ Author : 
//
//


#include "Product.h"

string Product::getName() {
    return name;
}

void Product::setName(string name) {
    this->name = name;
}

int Product::getID() {
    return id;
}

Product::Product(int id, string name) {
    this -> id = id;
    this -> name = name;
}

string Product::getProductNameByID(int id) {
    return id != NULL? getName() : "Product not found!";

}
void Product::setID(int id){
    this->id = id;
}

