//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ShoppingCart.h
//  @ Date : 16.03.2023
//  @ Author : 
//
//


#if !defined(_SHOPPINGCART_H)
#define _SHOPPINGCART_H

#include "Product.h"

class ShoppingCart {
public:
	void findProduct(Product *product);
};

#endif  //_SHOPPINGCART_H
