//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ShoppingCart.cpp
//  @ Date : 16.03.2023
//  @ Author : 
//
//


#include "ShoppingCart.h"
#include "Product.h"
#include <iostream>
using namespace std;
void ShoppingCart::findProduct(Product *product) {
    product->getProductNameByID(product->getID());
}

