//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.h
//  @ Date : 21.03.2023
//  @ Author : 
//
//


#if !defined(_USER_H)
#define _USER_H
#include <string>
#include "InternetProvider.h"

using namespace std;

class User {
public:
	void connectToTheInternet(InternetProvider provider);
	string getName();
	int getID();
	void setName(string name);
	void setID(int id);
private:
	string name;
	int id;
};

#endif  //_USER_H
