//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernoulie.h
//  @ Date : 09.05.2023
//  @ Author : 
//
//


#if !defined(_BERNOULIE_H)
#define _BERNOULIE_H

#include "Power.h"
#include "Newton.h"
#include <iostream>

using namespace std;

class Bernoulie {
public:
	void countBernoulie(double p, int n, int k);
	Bernoulie();
	~Bernoulie();
private:
	double argQ;
	long double argP;
	Power *pPower;
	Newton *pNewton;
};

#endif  //_BERNOULIE_H
