//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Factorial.cpp
//  @ Date : 09.05.2023
//  @ Author : 
//
//


#include "Factorial.h"

long double Factorial::factorial(int n) {
    return n==0 ? 1.0 : n * factorial(n-1);
}

