//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.cpp
//  @ Date : 09.05.2023
//  @ Author : 
//
//


#include "Newton.h"

Newton::Newton() {
    pFactorial = new Factorial();
}

Newton::~Newton() {
    delete pFactorial;
}

long double Newton::newton(int n, int k){
    N = n - k;
    long NbyK = 1;
    if(k >= N) {
        for (int i = k + 1; i <= n; i++) {
        NbyK *= i;
        }
        cout << "Nbyk : " <<NbyK <<endl;
        cout << "factorial" << pFactorial->factorial(n-k) <<endl;
        return (NbyK/pFactorial->factorial(n - k));
    }
    else {
        for(int i = N+1; i <= n; i++) {
            NbyK *= i;
        }
        cout << "Nbyk : " <<NbyK <<endl;
        cout << "factorial" << pFactorial->factorial(k) <<endl;
        return (NbyK / pFactorial->factorial(k));
    }
}

