//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.h
//  @ Date : 09.05.2023
//  @ Author : 
//
//


#if !defined(_NEWTON_H)
#define _NEWTON_H

#include "Factorial.h"
#include <iostream>
using namespace std;
class Newton {
public:
	Newton();
	~Newton();
	long double newton(int n,int k);
private:
	int N;
	Factorial *pFactorial;
};

#endif  //_NEWTON_H
