//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HDDDeviceFactory.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_HDDDEVICEFACTORY_H)
#define _HDDDEVICEFACTORY_H

#include "IDeviceFactory.h"
#include "IPCDevice.h"
#include "ILaptopDevice.h"
#include "IPCDevice.h"

class HDDDeviceFactory : public IDeviceFactory {
public:
	IPCDevice* fPCDevice();
	ILaptopDevice* fLaptopDevice();
};

#endif  //_HDDDEVICEFACTORY_H
