//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HDDLaptopDevice.cpp
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#include "HDDLaptopDevice.h"

void HDDLaptopDevice::displayDevice() {
    std::cout<<"HDD Laptop Device" <<std::endl;
}

