//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HDDLaptopDevice.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_HDDLAPTOPDEVICE_H)
#define _HDDLAPTOPDEVICE_H

#include "ILaptopDevice.h"


class HDDLaptopDevice : public ILaptopDevice {
public:
	void displayDevice();
};

#endif  //_HDDLAPTOPDEVICE_H
