//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HDDPCDevice.cpp
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#include "HDDPCDevice.h"

void HDDPCDevice::displayDevice() {
    std::cout<<"HDD PC Device" <<std::endl;
}

