//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HDDPCDevice.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_HDDPCDEVICE_H)
#define _HDDPCDEVICE_H

#include "IPCDevice.h"

class HDDPCDevice : public IPCDevice {
public:
	void displayDevice();
};

#endif  //_HDDPCDEVICE_H
