//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ILaptopDevice.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_ILAPTOPDEVICE_H)
#define _ILAPTOPDEVICE_H
#include <iostream>

class ILaptopDevice {
public:
	virtual void displayDevice() = 0;
};

#endif  //_ILAPTOPDEVICE_H
