//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IPCDevice.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_IPCDEVICE_H)
#define _IPCDEVICE_H
#include <iostream>

class IPCDevice {
public:
	virtual void displayDevice() = 0;
};

#endif  //_IPCDEVICE_H
