//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDDeviceFactory.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_SSDDEVICEFACTORY_H)
#define _SSDDEVICEFACTORY_H

#include "IDeviceFactory.h"
#include "IPCDevice.h"
#include "ILaptopDevice.h"

class SSDDeviceFactory : public IDeviceFactory {
public:
	IPCDevice* fPCDevice();
	ILaptopDevice* fLaptopDevice();
};

#endif  //_SSDDEVICEFACTORY_H
