//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDLaptopDevice.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_SSDLAPTOPDEVICE_H)
#define _SSDLAPTOPDEVICE_H

#include "ILaptopDevice.h"

class SSDLaptopDevice : public ILaptopDevice {
public:
	void displayDevice();
};

#endif  //_SSDLAPTOPDEVICE_H
