//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDLaptopDevice.cpp
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#include "SSDLaptopDevice.h"

void SSDLaptopDevice::displayDevice() {
    std::cout<<"SSD Laptop Device" <<std::endl;
}

