//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDPCDevice.h
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#if !defined(_SSDPCDEVICE_H)
#define _SSDPCDEVICE_H

#include "IPCDevice.h"

class SSDPCDevice : public IPCDevice {
public:
	void displayDevice();
};

#endif  //_SSDPCDEVICE_H
