//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSDPCDevice.cpp
//  @ Date : 21.06.2023
//  @ Author : 
//
//


#include "SSDPCDevice.h"

void SSDPCDevice::displayDevice() {
    std::cout<<"SSD PC Device"<<std::endl;
}

