//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Company.cpp
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#include "Company.h"

void Company::employeePushBack(Employee* employee) {
    employees.push_back(employee);
}

string Company::getCompanyName() {
    return companyName;
}

void Company::setCompanyName(string companyName) {
    this->companyName = companyName;
}

void Company::employeePopBack() {
    employees.pop_back();
    employees.empty() ? cout<< "There are no employees! "
                           : cout << "There is/are " <<employees.size() <<" employee/s"<<endl; ;
}

void Company::getEmployeeAtIndex(int i) {
    cout << "The employee at index " <<i << " is named " <<employees.at(i)->getName()
        <<" and has an ID of " <<employees.at(i)->getID()<<endl;
}

