//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Company.h
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#if !defined(_COMPANY_H)
#define _COMPANY_H
#include "Employee.h"


class Company {
public:
	void employeePushBack(Employee* employee);
	string getCompanyName();
	void setCompanyName(string companyName);
	void employeePopBack();
	void getEmployeeAtIndex(int i);
private:
	vector<Employee*> employees;
	string companyName;
};

#endif  //_COMPANY_H
