//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Employee.cpp
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#include "Employee.h"

int Employee::getID() {
    return employeeID;
}

string Employee::getName() {
    return employeeName;
}

void Employee::setID(int employeeID) {
    this->employeeID = employeeID;
}

void Employee::setName(string employeeName) {
    this->employeeName = employeeName;
}

Employee::Employee(int employeeID, string employeeName) {
    this->employeeID = employeeID;
    this->employeeName = employeeName;
}

Employee::~Employee() {
}

