//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Employee.h
//  @ Date : 23.03.2023
//  @ Author : 
//
//


#if !defined(_EMPLOYEE_H)
#define _EMPLOYEE_H
#include <iostream>
#include <string>
#include <vector>
using namespace std;

class Employee {
public:
	int getID();
	string getName();
	void setID(int employeeID);
	void setName(string employeeName);
	Employee(int employeeID, string employeeName);
	~Employee();
private:
	int employeeID;
	string employeeName;
};

#endif  //_EMPLOYEE_H
