//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CarToRent.h
//  @ Date : 28.03.2023
//  @ Author : 
//
//


#if !defined(_CARTORENT_H)
#define _CARTORENT_H
#include "Client.h"
#include <vector>
#include <iostream>
using namespace std;

class Client;
class CarToRent {
public:
	Client* getClient();
	void setClient(Client* client);
	string getName();
	void setName(string name);
	CarToRent(string name);
private:
	Client* client;
	string name;
};

#endif  //_CARTORENT_H
