//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.h
//  @ Date : 28.03.2023
//  @ Author : 
//
//


#if !defined(_CLIENT_H)
#define _CLIENT_H
#include <vector>
#include <iostream>
#include "CarToRent.h"
using namespace std;

class CarToRent;
class Client {
public:
	void getRentedCarAtIndex(int i);
	void rentCar(CarToRent* rentedCar);
	int getID();
	string getName();
	void setID(int id);
	void setName(string name);
	Client(int id, string name);
	void getAllRentedCars();
	void releaseAllCars();
	void releaseCarNumber(int i);
private:
	int id;
	string name;
	vector<CarToRent*> rentedCars;
};

#endif  //_CLIENT_H
