//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernoulie.h
//  @ Date : 17.05.2023
//  @ Author : 
//
//


#if !defined(_BERNOULIE_H)
#define _BERNOULIE_H
#include "Power.h"
#include "Newton.h"
#include <iostream>

using namespace std;

class Newton;
class Bernoulie {
public:
	Bernoulie();
	~Bernoulie();
	void countBernoulie(double p, int n, int k, Power* power, Newton* newton, Factorial* factorial);
private:
	double argQ;
	long double argP;
};

#endif  //_BERNOULIE_H
