//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernoulie.cpp
//  @ Date : 17.05.2023
//  @ Author : 
//
//


#include "Bernoulie.h"

Bernoulie::Bernoulie() {

}

Bernoulie::~Bernoulie() {

}

void Bernoulie::countBernoulie(double p, int n, int k, Power* power, Newton* newton, Factorial* factorial) {
    argQ = 1 - p;
    auto result = (newton->newton(n,k, factorial) *
                   power->power(p,k) *
                   power->power(argQ,n-k));
    cout << "Prawdopodobienstwo, ze w " << n << " doswiadczeniach "
         << k << " razy otrzymamy sukces wynosi " << result <<endl;

}

