//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Factorial.cpp
//  @ Date : 17.05.2023
//  @ Author : 
//
//


#include "Factorial.h"

long double Factorial::factorial(int n) {
    long double result = 1.0;
    for(int i=1; i<=n; i++){
        result *=i;
    }
    return result;
}

