//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Factorial.h
//  @ Date : 17.05.2023
//  @ Author : 
//
//


#if !defined(_FACTORIAL_H)
#define _FACTORIAL_H


class Factorial {
public:
	long double factorial(int n);
};

#endif  //_FACTORIAL_H
